version: '3.3'
services:
  vlc-chromecast:
    image: cleantoolbox/vlc-chromecast
    ports:
      - "8010:8010"
    container_name: vlc-chromecast
    environment:
      HOSTIP: "${HOSTIP:-192.168.1.39}"
      CHROMECASTIP: "${CHROMECASTIP:-192.168.1.43}"
    volumes:
    - "./samples:/samples"   
    command: ["-vvv", "--network-caching=2000","/samples/sample1.mp4", "--demux-filter=cc_demux", "--play-and-exit"]
  
